Numpy

◆mutable か immutable かは考慮するの忘れずに。
pythonは意図的にcopyしない限り基本参照渡し.その為,数値を変更する時は,mutable か immutable かは考慮するの忘れずに.
基本的な考え方としては，データ量が巨大になる可能性があるものはmutable，そうでなければimmutableと考えて良い．

mutable: list, set, dict

immutable: int, float, bool, str, tuple

https://datawokagaku.com/numpy_generate/

In [1]:
import numpy as np

In [2]:
def array_original(array):
 
    array[0] = 99
    return array
 
def array_copy(array):
    
    array_changed = array.copy()
    array_changed[0] = 99
    return array_changed

In [3]:
a = np.arange(1,10)
b = np.arange(1,10)

print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [4]:
print(array_original(a))
print(a)
#元のarrayが変更されてる

[99  2  3  4  5  6  7  8  9]
[99  2  3  4  5  6  7  8  9]


In [5]:
print(array_copy(b))
print(b)
#元のarrayが変更されてない

[99  2  3  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]
